# Práctica 1

[Ejercicios TF](http://jvanheld.github.io/LCG_BEII/practicals/motif_search_RegulonDB/motif_search_RegulonDB.html#collective_table_for_the_2020_practical)

## Introduction 
The goal of this practical is to evaluate the respective performances of two modes of representations for transcription factor binding motifs (TFBMs) to predict transcription factor binding sites (TFBS).

As reference genome we will use the strain **Escherichia_coli_GCF_000005845.2_ASM584v2**. 
- you can type `ASM584` in RSTAT web site 

## Choosing a TF on RegulonDB
- Each student will choose one transcription factor of interest having a reasonable number of binding sites (between 10 and 25).
- I choose `Nac` 

[URL to Nac DNA-binding transcriptional dual regulator regulonDB](http://regulondb.ccg.unam.mx/regulon?term=ECK120011265&format=jsp&objectName=Regulon&organism=ECK12&type=regulon#Multifun_Terms_of_regulated_genes)

- Conectarse a rsat.eu
[rstat.eu](http://pedagogix-tagc.univ-mrs.fr/rsat/RSAT_portal.html)


## Getting all upstream (“promoter”) sequences of E.coli

Open the tool retrieve-seq

Select organism **Escherichia_coli_GCF_000005845.2_ASM584v2** 

Set all parameters to get the non-coding sequences located upstream of all genes with a maximal distance of 400 bp from the gene start (i.e. relative coordinates from -1 to -400).

- $-1$ es el nucleótido antes del ATG
- Prevent overlap 
  - operones, las distancias intergénicas son muy cortas (10 bp) 
  - El codón de termino 
  - Casi todos están en sitios no codificantes 
- Label se puede elegir varios 
  - gene name 

Checo las secuencias 

- El gen previo 
- El numero de bases del fasta es que tanto se sobrelapan los genes o cuantas letras tienen de diferencia
  - Se ven los operones por ejemplo el de Histidina 
- Ahora tenemos todas las secuecnias de los genes río arriba

Copy the URL of the result file and save it in a text file (we will use it several times below)
[Result](http://embnet.ccg.unam.mx/rsat//tmp/apache/2021/03/01/retrieve-seq_2021-03-01.111023_VY7mAR.fasta)

### Coverage of the annotated binding sites by the reference motif

The question addressed here is to evaulate the relative performances of the consensus and PSSM to predict TFBSs and identify the target genes of our transcription factor of interest.

Note that the TFBS are expected to be found in the promoters of operon leader genes, and not in the upstream sequences of the other target genes (the genes following the leader in an operon). Thus, the reference gene set for this analysis are the leader genes of the operons regulated by our TF of interest.

Use dna-pattern to scan the annotated binding sites with the degenerate consensus.

Comentarios 

- quitamos los sequence limits pues en la mayoría de genes no hay sitios 
  - Los resultados te dicen cuantos sitios hay para tu motivo 
  - cómo explicas los sitios documentados en RegulonDB
    - se construye una matriz posición peso 
    - De ahí se construye el consensus 
    - Tengo un consensus que fue constuido por 15 sitios y solo encuentro 1 sitio en la búsqueda de Rstat
      - cuando yo impongo una c en la primera poisión entonces yo refuto todas las que tienen una A c o t
      - en la siguiente necesito una c y lugo una A 
      - nunca se deben utilizar consensus para encontrar regiones 
        - Es solo una forma de hablar de un sitio pero no para buscar 
- En Regulon DB anoto los stios 
- Consesnsus 

[Result](http://embnet.ccg.unam.mx/rsat/dna-pattern.cgi)

Use matrix-scan to scan the annotated binding sites with the RegulonDB matrix
[Result](http://embnet.ccg.unam.mx/rsat/matrix-scan.cgi)

Interpretation:

Compute the coverage rate of the two respective modes of representation (consensus versus matrix).

Compare the values and comment the results.

## Binding site prediction in all promoters 

Use the same tools (dna-pattern and matrix-scan) to predict binding sites in all the promoters of E.coli.

For matrix-scan, run the analysis with a threshold of p-value of either 0.001 or 0.0001.

Interpretation:

Compare the number of matches obtained in these respective searches.

With the respective p-values used for the scanning, how many matches would you expect by chance ?

Comment the results.


## Negative control 1: scan artificial sequences with your motif
As a negative control, we will run exactly the same analysis in sequences where there should be no specific site for our transcription factor. For this, we will generate

RSAT random-sequences, generate random sequences

use the same background model as you used to scan the promoter sequences in the above steps

use the promoter sequences retrieved above as model in order to obtain random sequences of the same sizes.

Run the same analysis as above (all promoters)

Interpretation:

How many sites were predicted?
How many sites would be expected by chance according to your parameters?
Do the two numbers correspond?

## Negative control 2: permute the columns of the matrix
A second type of negative control consists in scanning the actual biological sequences (all the promoters of E.coli, as analysed above), but to permute the columns of the PSSM. Such a permutation between the columns preserves statistical properties of the matrix (number of occurrences, information content of each column, total information content) but looses the biological information (the specific sequences recognized by the transcription factor).

Use the tool permute-matrix in order to generate 10 randomized copies of the motif

Send these randomiazed matrices to convert-matrix and check their logo.

Run the same analyses as above with the randomized matrix

Compare the number of sites obtained between the RegulonDB matrix and the randomized matrix derived from it.


## Matrix-based pattern matching 

Como se utiliza para escanear sitios potenciales 

- Transformamos los conteos convirtiendola en una matriz de frecuencia 
- Cada valor entre la suma de toda la columna 

Si en la primera posicion tengo una C me da $.25\% $  de pertencer a un sitio 

- Si en la segunda es T entonces es $0.13\%$
Es la suma de las probabilidades de cada columna 
- Existen columnas en donde la probabilidad de encontrar una G es $0\%$ entonces es imposible que se una si hay una G pues solo se encontro con $1 \%$ la T. 
  - No es lo que quiero, yo quiero que mi matriz sea más laxa, entonces la suavizo haciendo una pseudo-weight distributed according to residue priors 
  
  $f_i,j= (n_i,j +k/A)/sum()$

Se saca el producto pues se asume que son independientes 

Probabilidad dado el motivo 
$P(S|M)$
Probabilidad dado el background 
$P(S|B)$

- Se toma el máximo de cada columna para calcular una probabilidad máxima 
- Se puede calcular también el peor score 

En el genoma de coli más o menos tienen todas 0.25% de probabilidad 

## Oligo analysis

- le puedes dar secuencias y decirle que calcule la frecuencia de nucleótidos y dinucleótidos o kmers 1-8
- Te da las frecuencias observadas para cada nucleótido 
- la riqueza de a se refleja en la riqueza de dinucleotidos pero no es estricto 
- los trinucleotidos de tt aa 
- los tetranucleotidos son interesantes 
  - existe un tetranucleótido muy evitado en e.coli 
  - ctag 0.00046 tiene 266 apariciones comparado con 766 que es el siguiente 

## Seq-proba 

- puedo calcular la probabilidad de una secuencia dado un modelo 
- ejemplo ATGCGTAAAGCT
- dado el modelo ASM584
- proba_b tiene una probabilidad de $10^{-8}$
- Si la comparo con Saccharomyces cerevisiae 
  - modelo de markov 0 es la independencia o modelo de bernoulli 

1. Tenemos una matriz de conteos 
2. Calculamos auna matriz de frecuecnia a partir de la de conteos (puede considerarse como un modelo de proababilidad pero muy restrictivo pues los que tienen 0 los determina como imposible de encontrar )
3. Matriz de frecuencias corregidas 
  - Estimammos la probabilidad de una secuecnia dada el modelo 
4. Dado un modelo de bernoulli (independencia )  
- Solo multiplico la probabilidad de cada residudo dado el modelo de background (el peso de cada nucleótido ene le genom)
- puedo hacer el cociente ponderado 

$ln{frac{P(S|M)}{P(s)}$

la suma de los logaritmos es equivalente a la multiplicación de las probabilidades 


## Convert Background modell 

Matriz de transición entre un nucleótido y el siguiente 
Puedo calcular la probabilidad de un resiudo dado el residuo que le sigue 
cuando tengo una T la probabilidad de que despues exista una a es de .24 mientras que la probabilidad de que le siga otra t entonces es de 0.35

En RSAT metazoa background puedo buscar homo sapeins GRCh38 
calculo el modelo de markov de orden 1 

- en genomas de animales hay un CpG 
  - se encuentran en promotores con riqueza de CpG
  - son sitios de metilación del DNA que inactivan regiones enteras del cromosoma del humano 
  - regiones en donde hay muchas CpG están muy inactivadas por default 
  - es propio de los vertebrados 
  - Hay fuertes dependencias entre nucleótidos, generalementa a una a le precede otra a 
    - comportamiento agregantivo de aa y de tt
    - en e.coli hay un tetra nucleótido evidado 
    - en homo sapiens hay un dinucleotido evitado CpG

## Position scanning matrix 

Acepto un falso positivo cada 10,000 pares de bases y escane 1 millon 47 mill 
Espero 104 

Nb of known operon leader genes amond predictions with pssm
son los que sí encontré d elos operones que salen en regulon db 

operon sensitivity with PSSSM
son los que encontre / todos los que existen 

