# Descubrimiento de motivos

## Historia 

Predecir los sitios sería importante pero más adelante se va a caracterizar la transcriptómica 
Si yo te doy un grupo de genes que responde a una fuente de nitrógeno.

## Motif discovery 

- solo existían microarreglos 
- Yo tengo 20 genes cooregulados y quiero saber cuales son los motivos y los sitios en sus promotores 
- Te doy genes, no te doy el motivo 
  - se sabe que existe un factor transcripcional que regula a todos los genes 
  - El factor puede pegarse en cualquiera de las dos direcciones 
    - Hace una rotación cada 10.5 nucleotidos 
    - Estamos en un espacio 3D 
    - los sitios de interacción entre el factor y el DNA son muy cortos

- 7 genes que se expresan en ausencia de metionina MET
- 7 genes expresados en bajas condiciones de nitrógeno NIT
- 5 genes expresado bajo estrés de fosfato PHO

1. Verificar en los 7 genes de nitrogeno si se enocntraba o no el motivo gataag y cuantas ocurrencias 
- Se analiza los genes río arriba 
- los 4 regulones su palabra más frecuente era aaaaaa
- Se sabía en levadura que el hecho de encontrar en una cadena u otra el sitio no importaba 
  - Se agrupa cada hexanucleótido con su reversa complementaria 
  - ordenados por número de ocurrencias 
  - los hexanucleótidos correctos en azul
    - tenía una frecuencia media como de 10 

**¿Cómo saber cuales son las correctas?**

- Desarrollar un modelo para calcular la frecuencia observada 
- Comparar las ocurrencias observadas vs lo que esperas al azar 
- Las frecuencias de hexanucleótidos varian mucho entre codificante y no codificante 
- comparas las ocurrencias observadas en coding vs intergenic sequences 
- las probabilidades de encontrar un hexanucleótido son distintas entre distintos organismos 
- GATAAG, cual es la que tiene más ocurrencias observadas vs las que espero de ella 

Contamos 
positivos = posiciones en donde tenoms la palabra
contamos = todas las posiciones en donde no tenemos CATG
metionina y no metionina = si sale una dependencia muy fuerte entonces tenemos un p-value 

- z socre reposa en normalidad 
- modelo de bernoulli 
  - en cada posición inica un hexanucleótido, exito o fracas
  - en cada posición checo si tengo éxito o fracaso 
  - cuento en metionina en 5000 posiciones y en cada posición checo los exitos y los fracasos 
  - Checo con el modelo de Bernoulli 
  - Tengo las frecuencias de observar 
  
## Modelo de Bernoulli 

- para calcular un p-value
- para calcular un e-value 

- Ejemplo 
  - para nitrogeno 
  - sobrelapan y parece ser parte de un heptanucleotido 
  - CACGTG 12 ocurrencias y espero menos de 1 
  
¿Cómo defino el punto de corte para poner un valor de p?
Una medida de que tan lejos está de la diagonal es observed/expected ratio 
  - eso nunca debe usarse en estadística 

- Log-likelihood ratio 
  - necesitas muchos observados 

- z-score
  - supone una distribución normal

- Poisson 

- Binomial (Jacques)
  - Probabilidad de observar 26 ocurrencias con un modelo de bernoulli 
  - vamos a detectar los kmers
  - 

    
## Background model 

- Existen dependencias 
  - más AA en el genoma 
  - Representación es mejor con modelos de Markov 
- consensus 


### Aproximaciones basadas en matrices 

- Giibbs (stochastich EM)


## Ejercicio 2 

Elegir un factor transcripcional 
- Elegí PHO
Sacar sus secuencias upstream 
default = -1 a -800

1. Correr oligoanálisis para descubrir motivos 
- Se deja genome subset para estimar la frecuencia de hexanucleótidos

[oligoanálisis](http://rsat-tagc.univ-mrs.fr/rsat/oligo-analysis.cgi)

2. Mandar los resultados a DNA pattern

[dna pattern](http://rsat-tagc.univ-mrs.fr/rsat/dna-pattern.cgi)

3. Manadar las ocurrencias de hexanucleotidos a feature-map para visualizar  
[feature map](http://rsat-tagc.univ-mrs.fr/rsat/feature-map.cgi)


## Generate random seq of the same size as the upstream sequences of your region
- Select a random set of genes of the same size as your regulons 
[random sequence result](http://embnet.ccg.unam.mx/rsat/random-seq.cgi)
- Do the same analysis
  - oligonucleotide analysis 6,7,8 
  
- Report the results (max sig)


Si elegimos un conjunto de genes que tienen regulación diversa entonces no se espera que tengamos motivos 
- p valor nominal 
  - estamos haciendo muchas pruebas estadísticas en paralelo 
  - en promedio una palabra sobrerepresentada puede salir cada 1.79E-12
  - probabilidad de observar algo tan extremo como lo que observamos 
  - hipótesis nula 
    - el promedio es igual entre las dos poblaciones 
    - vamos a tomar una palabra a la vez 
      - esta palabra en la población (el conjunto de todos los genes que responden al PHO en la levadura)
      - la palabra tiene la misma frecuencia en los promotores de los genes PHO que en todos los otros promotores, la frecuencia de eventos en un esquema de bernoulli (exito es observar dicha palabra , fracaso es observar otra palabra) 
  - Si yo hubiera seleccionado genes que no tienen 
    - se rechaza la hipótesis null y generalemnte se toma un p-value de menos de 0.05%

24 personas, una pistola , 1 bala 1 cargador
  - 1/6 
  - esperanza de estudiantes que no saldrán vivos 
    - 24/6
    - 4^6 nucleotidos son 4096 
    - 4096/2 = 2048 pero hay 2080 por que tenemos 3^6 palabras reverse complementary palindromicas 
      - 4096 palabras de 6 en total 4^3 reverese complementarias = 64
        - 4096
        -k = 6
        - nb k-mers = 4096
        - nb of palindroms = 4^6/2 = 64
          - los impares no tienen palíndromos 
        - nb of non-palindromic kmers 4096
          - 4096-64= 
- Rechazar la hipótesis nul cuando estamos en la hipotesis null = falso positivo 
  - Nb distinct after RC grouping 2080 
  - CAGCTG | CAGCTG
  el evalor es el p valor por el número de pruebas que es 2080
  significancia -log10 del e valor 
    - si es alta tengo algo bueno 
     - si está baja no es muy confiable 
     - significancia de 1 se espera 1 vez entre 10 
     - de 2 una vez entre 100
     - cuando se incorporan genomas de la mitocondria puede tener sesgos 
     - la composición nucleotídica de la mitocondria es muy distinta
      - frecuencia de A y T muy grande 
        - generalmente los promotores de mitocondria son ricos en ATTA

- Gal4 factor no es significativo 
  - Toca los dos puntos de contacto con una separación de bases 
    - motivos separados 
    - Cuentas las parejas de oligonucleotidos espaciadas con dyad-analysis result 
      - analias todos los espacios posibles de 0 a 20 
      cggn{12}cga
      - Ensamblas las diadas y obtienes un score 
      - para detectar motivos espaciados 
    
  - helix turn helix 
    - toca dna en dos puntos de contacto y se esablecen interacciones moleculares 
      - 
1. conozco motivo 
  - quiero escanar secuencia para busqueda de patrones conocidos 
2. no conzco los motivos 
    - se que están corregulados y quiero descubrirlos 
3. Chi   
      
